import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { CountriesProvider } from "../contexts/CountriesContext";

const openSans = Open_Sans({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased font-sans bg-gray-50`}
      >
        <CountriesProvider>
          {children}
        </CountriesProvider>
      </body>
    </html>
  );
}
